=== YousufNaveedKhan/DataProcessingwithXMLandJSON/Lec03-XML-Schema/04-XSD-ComplexTypes/students.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="students">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="student" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="id" type="xsd:integer" />
                            <xsd:element name="name" type="xsd:string" />
                            <xsd:element name="age">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:integer">
                                        <xsd:minExclusive value="10" />
                                        <xsd:maxExclusive value="50" />
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:choice>
                                <xsd:element name="phone" type="xsd:integer" />
                                <xsd:element name="email" type="xsd:string" />
                            </xsd:choice>
                            <xsd:element name="course" type="xsd:string" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== YousufNaveedKhan/DataProcessingwithXMLandJSON/Lec03-XML-Schema/04-XSD-ComplexTypes/students.xml
<?xml version="1.0" encoding="UTF-8"?>

<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="students.xsd">
    <student>
        <id>10001</id>
        <name>Rajab</name>
        <age>22</age>
        <email>rajab@gmail.com</email>
        <course>ADSE</course>
    </student>
        <student>
        <id>10002</id>
        <name>Taha</name>
        <age>21</age>
        <phone>03312345678</phone>
        <course>ADSE</course>
    </student>
    <student>
        <id>10003</id>
        <name>Abdul Rehman</name>
        <age>19</age>
        <phone>03312343678</phone>
        <course>ADSE</course>
    </student>
    <student>
        <id>10004</id>
        <name>Ghulam Muhammad</name>
        <age>18</age>
        <email>ghulammuhammad@gmail.com</email>
        <course>ADSE</course>
    </student>

</students>
